// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getEnv(key: string): string | undefined {
  // Vite substitui import.meta.env.VITE_* em build-time. process.env só existe no servidor.
  const viteVal =
    typeof import.meta !== "undefined" &&
    (import.meta as unknown as { env?: Record<string, string | undefined> }).env?.[key];
  if (viteVal) return viteVal;
  if (typeof process !== "undefined" && process.env) {
    return process.env[key.replace(/^VITE_/, "")] ?? process.env[key];
  }
  return undefined;
}

function createSupabaseClient() {
  // URL e chave PUBLISHABLE são públicas por design (vão para o bundle do
  // navegador em todo build). Os fallbacks abaixo garantem que o app publicado
  // funcione mesmo quando a hospedagem compila sem VITE_* configurado.
  // Se as envs existirem, elas têm precedência. NUNCA colocar chaves secret/
  // service_role aqui — essas ficam só no servidor (client.server.ts).
  const SUPABASE_URL =
    getEnv("VITE_SUPABASE_URL") ?? "https://yrkdbrkijpwilhptmqii.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    getEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ??
    "sb_publishable_ZAcaq2p3P4SsJX1fQSrtWA_RO2p97rB";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
